server:
  port: 7100


spring:
  application:
    name: quickTaxi-eurekaServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    # 关闭 read 缓存 直接从write 缓存中获取 便于开发
    use-read-only-response-cache: false
  instance:
    hostname: eureka-server