server:
  port: 80


spring:
  application:
    name: quicktaxi-gateway


  cloud:
    loadbalancer:
      #禁用ribbon 使用loadbalancer
      ribbon:
        enabled: false

    gateway:
      routes:
        - id: sms
          uri: lb://quickTaxi-sms
          predicates:
            - Path=/sms/**
          filters:
            - StripPrefix=1

        - id: verificationCode
          uri: lb://quickTaxi-verificationCode
          predicates:
            - Path=/verification/**
          filters:
            - StripPrefix=1

        - id: user
          uri: lb://quickTaxi-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

  redis:
    port: 6379
    host: localhost


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/


security:
  ignore:
    whites:
      - /user/login
      - /verify-code/generate/**



