server:
  port: 80


spring:
  application:
    name: quicktaxi-gateway


  cloud:
    loadbalancer:
      #禁用ribbon 使用loadbalancer
      ribbon:
        enabled: false

    gateway:
      routes:
        - id: sms
          uri: lb://quickTaxi-sms
          predicates:
            - Path=/sms/**
          filters:
            - StripPrefix=1

        - id: verificationCode
          uri: lb://quickTaxi-verificationCode
          predicates:
            - Path=/verification/**
          filters:
            - StripPrefix=1

        - id: user
          uri: lb://quickTaxi-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
    # nacos
    nacos:
      # 服务发现
      discovery:
        server-addr: localhost:8848
        group: quickTaxi


      # 配置中心
      config:
        server-addr: localhost:8848
        group: quickTaxi


  redis:
    port: 6379
    host: localhost





security:
  ignore:
    whites:
      - /**/user/login
      - /**/verify-code/generate/**
      - /**/swagger-ui.html
      - /**/swagger-resources/**
      - /**/swagger-resources
      - /**/v2/api-docs
      - /**/swagger-resources/configuration/ui


