server:
  port: 8001


spring:
  application:
    name: quickTaxi-verificationCode
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
