spring:
  application:
    name: quickTaxi-order

  # redis配置
  redis:
    host: localhost
    port: 6379

  cloud:
    # sentinel dashboard配置
    sentinel:
      transport:
        dashboard: localhost:8081
      # 服务启动后 直接注册到dashboard
      eager: true
      datasource:
        redis:
          host: localhost

    # nacos
    nacos:
      # 服务发现
      discovery:
        server-addr: localhost:8848
        group: quickTaxi


      # 配置中心
      config:
        server-addr: localhost:8848
        group: quickTaxi


server:
  port: 8004
  servlet:
    context-path: /order


# eureka(废弃)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/




