spring:
  application:
    name: quickTaxi-user


  redis:
    host: localhost
    port: 6379

server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/


