server:
  port: 8002


spring:
  application:
    name: quickTaxi-sms
  cloud:
    # nacos
    nacos:
      # 服务发现
      discovery:
        server-addr: localhost:8848
        group: quickTaxi


      # 配置中心
      config:
        server-addr: localhost:8848
        group: quickTaxi

